// Generated by Wrangler on Sat Jun 15 2024 15:10:42 GMT+0900 (대한민국 표준시)
// by running `wrangler types`

interface Env {
	JWT_SECRET: string;
	REFRESH_TOKEN_SECRET: string;
	AUTH_CODE_SECRET: string;
	DB: D1Database;
}
