compatibility_date = "2024-03-16"
node_compat = true

[[d1_databases]]
binding = "DB"
database_name = "beomjun-kr"
database_id = "9481dcf4-2348-4a0b-8235-3159ad8b3dd0"
preview_database_id = "DB"

[env.preview]
name = "preview"
[[env.preview.d1_databases]]
binding = "DB"
database_name = "preview-beomjun-kr"
database_id = "cf78f713-d63b-4ccd-af27-0744c4ec426c"
